=== Logiqx/caesar/dtd/caesar.dtd
<!--================ Character mnemonic entities =========================-->

<!ENTITY % HTMLlat1 PUBLIC
   "-//W3C//ENTITIES Latin 1 for XHTML//EN"
   "xhtml-lat1.ent">
%HTMLlat1;

<!ENTITY % HTMLsymbol PUBLIC
   "-//W3C//ENTITIES Symbols for XHTML//EN"
   "xhtml-symbol.ent">
%HTMLsymbol;

<!ENTITY % HTMLspecial PUBLIC
   "-//W3C//ENTITIES Special for XHTML//EN"
   "xhtml-special.ent">
%HTMLspecial;

<!--================ My structures =========================-->

<!ELEMENT emulator_link (name, version, date, homepage+, author_link+, emulates, comment, platform)>
<!ATTLIST emulator_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT old_name (name, emulator_link)>

<!ELEMENT author_link (name)>
<!ATTLIST author_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT library_link (name, version, date, homepage, author_link+, emulates, comment)>
<!ATTLIST library_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT tool_link (name, version, date, homepage, author_link+, comment)>
<!ATTLIST tool_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT name (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT emulates (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT crc (#PCDATA)>
<!ELEMENT mame (#PCDATA)>
<!ELEMENT rombuild (#PCDATA)>
<!ELEMENT homepage (#PCDATA)>
<!ATTLIST homepage status CDATA "">
<!ELEMENT comment (#PCDATA | a)*>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA "">
<!ELEMENT status (#PCDATA)>
<!ELEMENT platform (#PCDATA)>

<!ELEMENT author (name, email*, emulator_links?, contribution_links?, cpu_links?, graphics_links?, sound_links?, tool_links?)>
<!ELEMENT emulator_links (emulator_link*, old_name*)>
<!ELEMENT contribution_links (emulator_link+)>
<!ELEMENT cpu_links (library_link+)>
<!ELEMENT graphics_links (library_link+)>
<!ELEMENT sound_links (library_link+)>
<!ELEMENT library_links (library_link+)>
<!ELEMENT tool_links (tool_link+)>

<!ELEMENT emulator (name, version, date, homepage+, author_link+, contributors?,
	emulates, comment, status,
	cpu_links?, tool_links?, platform, controllers?, features, files?, relatives?, snaps?, game_links?)>
<!ATTLIST emulator dat CDATA "" dat_type CDATA "" id CDATA "" type CDATA "">
<!ELEMENT contributors (contributor+)>
<!ELEMENT contributor (author_link, comment?)>
<!ELEMENT controllers (controller+)>
<!ELEMENT controller (#PCDATA)>

<!ELEMENT features (sound?, source?, screendump?, hiscoresave?, savegame?,
	recordinput?, dips?, cheat?, autoframeskip?, throttle?, network?, recordsound?, rotate?)>
<!ELEMENT sound (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT screendump (#PCDATA)>
<!ELEMENT hiscoresave (#PCDATA)>
<!ELEMENT savegame (#PCDATA)>
<!ELEMENT recordinput (#PCDATA)>
<!ELEMENT dips (#PCDATA)>
<!ELEMENT cheat (#PCDATA)>
<!ELEMENT autoframeskip (#PCDATA)>
<!ELEMENT throttle (#PCDATA)>
<!ELEMENT network (#PCDATA)>
<!ELEMENT recordsound (#PCDATA)>
<!ELEMENT recordmovie (#PCDATA)>
<!ELEMENT rotate (#PCDATA)>

<!ELEMENT files (file+)>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file name CDATA "" size CDATA "">

<!ELEMENT relatives (predecessors?, derivative_of?, hybrid_of?, modification_of?, port_of?, alt_versions?, ports?, modified_versions?, derivatives?, successors?)>
<!ELEMENT predecessors (emulator_link+)>
<!ELEMENT derivative_of (emulator_link+)>
<!ELEMENT hybrid_of (emulator_link+)>
<!ELEMENT modification_of (emulator_link+)>
<!ELEMENT port_of (emulator_link+)>
<!ELEMENT alt_versions (emulator_link+)>
<!ELEMENT ports (emulator_link+)>
<!ELEMENT modified_versions (emulator_link+)>
<!ELEMENT derivatives (emulator_link+)>
<!ELEMENT successors (emulator_link+)>

<!ELEMENT game_groups (game_group+)>
<!ELEMENT game_group (name, manufacturer, year, non_mame, game_links)>
<!ATTLIST game_group id NMTOKEN "">
<!ELEMENT game_links (game_link+)>
<!ELEMENT game_link (name, manufacturer, year, size, non_mame?, emulator_link?)>
<!ELEMENT non_mame (#PCDATA)>
<!ATTLIST game_link emu_id NMTOKEN "" emu_type NMTOKEN "" game_id NMTOKEN "">

<!ELEMENT game (emulator_link, game_group_link, name, manufacturer, year, size, audio?, input?, video?, chips?, driver?, snaps?, roms?)>
<!ATTLIST game emu_id NMTOKEN "" emu_type NMTOKEN "" game_id NMTOKEN "">
<!ELEMENT game_contents (title, game_group_links)>
<!ELEMENT mame_games (title, game_links)>
<!ELEMENT game_group_links (game_group_link+)>
<!ELEMENT game_group_link (name, manufacturer, year, non_mame)>
<!ATTLIST game_group_link file_id NMTOKEN "" grp_id NMTOKEN "">
<!ELEMENT roms (rom+)>
<!ELEMENT rom (name, size, crc, mame, rombuild)>
<!ELEMENT snaps (snap+)>
<!ELEMENT snap (#PCDATA)>
<!ATTLIST snap width NMTOKEN "" height NMTOKEN "">
<!ELEMENT audio (channels?)>
<!ELEMENT channels (#PCDATA)>
<!ELEMENT input (players, control?, buttons?, coins?, service?, tilt?)>
<!ELEMENT players (#PCDATA)>
<!ELEMENT control (#PCDATA)>
<!ELEMENT buttons (#PCDATA)>
<!ELEMENT coins (#PCDATA)>
<!ELEMENT service (#PCDATA)>
<!ELEMENT tilt (#PCDATA)>
<!ELEMENT video (screen, orientation, x?, y?, colors?, freq)>
<!ELEMENT screen (#PCDATA)>
<!ELEMENT orientation (#PCDATA)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT colors (#PCDATA)>
<!ELEMENT freq (#PCDATA)>
<!ELEMENT chips (chip+)>
<!ELEMENT chip (type, name, clock?, flags?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT clock (#PCDATA)>
<!ELEMENT flags (#PCDATA)>
<!ELEMENT driver (status, color, sound)>
<!ELEMENT color (#PCDATA)>

<!ELEMENT library (name, version, date, homepage, author_link+, emulates, comment, emulator_links?, tool_links?, files?, library_relatives?)>
<!ATTLIST library id NMTOKEN "" type NMTOKEN "">

<!ELEMENT library_relatives (library_predecessors?, library_descendants?)>
<!ELEMENT library_predecessors (library_link+)>
<!ELEMENT library_descendants (library_link+)>

<!ELEMENT emulator_contents (title, comment, emulator_links?)>
<!ELEMENT library_contents (title, comment, library_links?)>
<!ELEMENT tool_contents (title, comment, tool_links?)>

<!ELEMENT tool (name, version, date, homepage, author_link+, comment, emulator_links?, library_links?, files?, tool_relatives?)>
<!ATTLIST tool id NMTOKEN "" type NMTOKEN "">

<!ELEMENT tool_relatives (tool_predecessors?, tool_descendants?)>
<!ELEMENT tool_predecessors (tool_link+)>
<!ELEMENT tool_descendants (tool_link+)>

=== Logiqx/caesar/data/libs/cpu/turbo68k.xml
<?xml version="1.0"?>
<!DOCTYPE library SYSTEM "../../../dtd/caesar.dtd">
<library id="turbo68k" type="cpu">
	<name>Turbo68K</name>
	<version>0.60</version>
	<date>19/01/2002</date>

	<homepage>http://dynarec.com/~bart/turbo68k/</homepage>
	<author_link id="bart_trzynadlowski">&author_bart_trzynadlowski;</author_link>

	<emulates>M68000 (Motorola)</emulates>
	<comment>Written in x86 assembler. Previously known as Genital68K. Fast and accurate</comment>

	<emulator_links>
		<emulator_link id="gxp" type="sound">&emulator_gxp;</emulator_link>
	</emulator_links>

	<files>
		<file name="t68k060.zip">CPU Emulator</file>
		<file name="68kdb060.zip">68000 Disassembler for use with Genital68K</file>
	</files>
</library>

=== Logiqx/caesar/data/emus/single/jasmappy.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="jasmappy" type="single" dat="JAS-Mappy_v1.0">
	<name>JAS-Mappy (JROK's Arcade Simulator)</name>
	<version>1.0</version>
	<date>16/07/1997</date>

	<homepage>http://www.jrok.com/</homepage>
	<author_link id="jrok">&author_jrok;</author_link>

	<emulates>Mappy (Namco)</emulates>
	<comment>Grew up to become the multi-arcade emulator JAS</comment>
	<status>Now part of JAS</status>

	<tool_links>
		<tool_link id="watcom" type="compilers">&tool_watcom;</tool_link>
	</tool_links>

	<platform>DOS (but Windows friendly)</platform>

	<controllers>
		<controller>Keyboard</controller>
		<controller>Joystick</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>No</source>
		<screendump>No</screendump>
		<hiscoresave>Yes</hiscoresave>
		<savegame>Yes</savegame>
		<recordinput>No</recordinput>
		<dips>Yes</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
	</features>

	<files>
		<file name="jas-mapy.zip">Emulator</file>
	</files>

	<relatives>
		<successors>
			<emulator_link id="jas" type="multi">&emulator_jas;</emulator_link>
		</successors>
	</relatives>
</emulator>

=== Logiqx/caesar/data/authors/roberto_ventura.xml
<?xml version="1.0"?>
<!DOCTYPE author SYSTEM "../../dtd/caesar.dtd">
<author id="roberto_ventura">
	<name>Roberto Ventura</name>
	<email>jdoe@galactica.it</email>
	<email>jdoe@micronet.it</email>
	<emulator_links>
		<emulator_link id="ghostsngoblins" type="single">&emulator_ghostsngoblins;</emulator_link>
		<emulator_link id="jff" type="multi">&emulator_jff;</emulator_link>
		<emulator_link id="system8" type="multi">&emulator_system8;</emulator_link>
		<emulator_link id="vastar" type="single">&emulator_vastar;</emulator_link>
	</emulator_links>
</author>

=== Logiqx/caesar/data/emus/multi/ace.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="ace" type="multi" dat="ACE_v1.9">
	<name>ACE (Another Capcom Play System Emulator)</name>
	<version>1.9</version>
	<date>24/02/2002</date>

	<homepage>http://ace.emuunlim.com/</homepage>
	<author_link id="rollback">&author_rollback;</author_link>

	<emulates>Capcom CPS-1, CPS-2 and Neo-Geo games</emulates>
	<comment>One of many Capcom/SNK emulators. When the author lost his latest source code in a hard disk crash, he didn't want to continue it any longer.</comment>
	<status>Discontinued</status>

	<cpu_links>
		<library_link id="musashi" type="cpu">&library_musashi;</library_link>
		<library_link id="multiz80" type="cpu">&library_multiz80;</library_link>
	</cpu_links>

	<tool_links>
		<tool_link id="msvc" type="compilers">&tool_msvc;</tool_link>
		<tool_link id="midas" type="snd_libs">&tool_midas;</tool_link>
		<tool_link id="zlib" type="zip_libs">&tool_zlib;</tool_link>
	</tool_links>

	<platform>Windows</platform>

	<controllers>
		<controller>Keyboard</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>Yes</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>No</savegame>
		<recordinput>No</recordinput>
		<dips>No</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
	</features>

	<files>
		<file name="ace19.zip">Emulator</file>
		<file name="ace18src.zip">Source</file>
		<file name="sgemf.zip">Super Gem Fighter driver - the last thing released!</file>
	</files>
</emulator>

=== Logiqx/caesar/data/authors/daniel_boris.xml
<?xml version="1.0"?>
<!DOCTYPE author SYSTEM "../../dtd/caesar.dtd">
<author id="daniel_boris">
	<name>Daniel Boris</name>
	<email>danlb_2000@yahoo.com</email>
	<email>dboris@comcast.net</email>
	<emulator_links>
		<emulator_link id="cloakanddagulator" type="single">&emulator_cloakanddagulator;</emulator_link>
		<emulator_link id="discretesim" type="single">&emulator_discretesim;</emulator_link>
	</emulator_links>
	<contribution_links>
		<emulator_link id="mame" type="multi">&emulator_mame;</emulator_link>
		<emulator_link id="dice" type="multi">&emulator_dice;</emulator_link>
	</contribution_links>
</author>

=== Logiqx/caesar/data/emus/single/amoad.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="amoad" type="single" dat="AMOAD_I_-_XXII">
	<name>AMOAD (Arcade Machine On A Disk)</name>
	<version>-only version-</version>
	<date>05/07/1998</date>

	<homepage>http://surf.to/amoad</homepage>
	<author_link id="tony_docherty">&author_tony_docherty;</author_link>
	<author_link id="marcel_silvius">&author_marcel_silvius;</author_link>

	<emulates>Various Games</emulates>
	<comment>A collection of single emulators that each fit on a floppy disk. Binaries for AMOAD 20+22 are missing (they need re-compiling with Allegro v3.0 and SEAL v1.03).</comment>
	<status>Dormant</status>

	<cpu_links>
		<library_link id="z80" type="cpu">&library_z80;</library_link>
		<library_link id="z80em" type="cpu">&library_z80em;</library_link>
	</cpu_links>

	<tool_links>
		<tool_link id="djgpp" type="compilers">&tool_djgpp;</tool_link>
		<tool_link id="allegro" type="gfx_libs">&tool_allegro;</tool_link>
	</tool_links>

	<platform>DOS</platform>

	<controllers>
		<controller>Keyboard</controller>
		<controller>Joystick</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>Yes</source>
		<screendump>Yes</screendump>
		<hiscoresave>Yes</hiscoresave>
		<savegame>No</savegame>
		<recordinput>No</recordinput>
		<dips>Yes</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
		<network>No</network>
		<recordsound>No</recordsound>
		<rotate>No</rotate>
	</features>

	<files>
		<file name="amoad1.zip">AMOAD 1 (Space Invaders)</file>
		<file name="amoad2.zip">AMOAD 2 (Space Invaders Pt II)</file>
		<file name="amoad2s.zip">AMOAD 2 (Space Invaders Pt II) - Source</file>
		<file name="amoad3.zip">AMOAD 3 (Galaxy Wars)</file>
		<file name="amoad3s.zip">AMOAD 3 (Galaxy Wars) - Source</file>
		<file name="amoad4.zip">AMOAD 4 (Invaders Revenge)</file>
		<file name="amoad4s.zip">AMOAD 4 (Invaders Revenge) - Source</file>
		<file name="amoad5.zip">AMOAD 5 (Lunar Rescue)</file>
		<file name="amoad5s.zip">AMOAD 5 (Lunar Rescue) - Source</file>
		<file name="amoad6.zip">AMOAD 6 (Space Attack II)</file>
		<file name="amoad6s.zip">AMOAD 6 (Space Attack II) - Source</file>
		<file name="amoad7.zip">AMOAD 7 (Super Earth Invasion)</file>
		<file name="amoad7s.zip">AMOAD 7 (Super Earth Invasion) - Source</file>
		<file name="amoad8.zip">AMOAD 8 (Asteroids)</file>
		<file name="amoad8s.zip">AMOAD 8 (Asteroids) - Source</file>
		<file name="amoad9.zip">AMOAD 9 (Bombjack)</file>
		<file name="amoad10.zip">AMOAD 10 (Galaxian)</file>
		<file name="amoad11.zip">AMOAD 11 (Frogger)</file>
		<file name="amoad12.zip">AMOAD 12 (Galaga)</file>
		<file name="amoad13.zip">AMOAD 13 (Cosmic Monsters)</file>
		<file name="amoad13s.zip">AMOAD 13 (Cosmic Monsters) - Source</file>
		<file name="amoad14.zip">AMOAD 14 (Phoenix)</file>
		<file name="amoad15.zip">AMOAD 15 (Ms Pacman)</file>
		<file name="amoad15s.zip">AMOAD 15 (Ms Pacman) - Source</file>
		<file name="amoad16.zip">AMOAD 16 (Amidar)</file>
		<file name="amoad16s.zip">AMOAD 16 (Amidar) - Source</file>
		<file name="amoad17.zip">AMOAD 17 (Crazy Kong)</file>
		<file name="amoad17s.zip">AMOAD 17 (Crazy Kong) - Source</file>
		<file name="amoad18.zip">AMOAD 18 (Pacman)</file>
		<file name="amoad18s.zip">AMOAD 18 (Pacman) - Source</file>
		<file name="amoad19.zip">AMOAD 19 (Pengo)</file>
		<file name="amoad19s.zip">AMOAD 19 (Pengo) - Source</file>
		<file name="amoad20s.zip">AMOAD 20 (Scramble) - Source</file>
		<file name="amoad21.zip">AMOAD 21 (Crush Roller)</file>
		<file name="amoad21s.zip">AMOAD 21 (Crush Roller) - Source</file>
		<file name="amoad22s.zip">AMOAD 22 (Crazy Climber) - Source</file>
	</files>

	<relatives>
		<predecessors>
			<emulator_link id="asteroids" type="single">&emulator_asteroids;</emulator_link>
			<emulator_link id="spaceinvaders" type="multi">&emulator_spaceinvaders;</emulator_link>
		</predecessors>
	</relatives>
</emulator>

=== Logiqx/caesar/data/emus/single/annoid.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="annoid" type="single" dat="Annoid_v1.0">
	<name>Annoid</name>
	<version>1.1</version>
	<date>15/11/2000</date>

	<homepage>http://www.ganksoft.com/</homepage>
	<author_link id="brian_peek">&author_brian_peek;</author_link>

	<emulates>Arkanoid (Taito)</emulates>
	<comment>Emulates Arkanoid using the bootleg ROMset.</comment>
	<status>Dormant</status>

	<cpu_links>
		<library_link id="z80em" type="cpu">&library_z80em;</library_link>
	</cpu_links>

	<tool_links>
		<tool_link id="seal" type="snd_libs">&tool_seal;</tool_link>
		<tool_link id="msvc" type="compilers">&tool_msvc;</tool_link>
	</tool_links>

	<platform>Windows</platform>

	<controllers>
		<controller>Keyboard</controller>
		<controller>Mouse</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>No</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>Yes</savegame>
		<recordinput>No</recordinput>
		<dips>Yes</dips>
		<cheat>Yes</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
	</features>

	<files>
		<file name="annoid11.zip">Emulator</file>
	</files>
</emulator>

=== Logiqx/caesar/data/emus/wince/laser_ipaq.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="laser_ipaq" type="wince" dat="dummy">
	<name>Laser (Compaq Ipaq)</name>
	<version>0.9</version>
	<date>30/10/2000</date>

	<homepage>http://www.laseremu.com/</homepage>
	<author_link id="domenico_dato">&author_domenico_dato;</author_link>

	<emulates>Midway 8080 based games like space invaders</emulates>
	<comment>Compaq Ipaq port of Laser</comment>
	<status>Dormant</status>

	<platform>WinCE</platform>

	<controllers>
		<controller>Buttons</controller>
	</controllers>

	<features>
		<sound>No</sound>
		<source>No</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>No</savegame>
		<recordinput>No</recordinput>
		<dips>No</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
		<rotate>No</rotate>
	</features>

	<relatives>
		<port_of>
			<emulator_link id="laser" type="multi">&emulator_laser;</emulator_link>
		</port_of>
	</relatives>
</emulator>
