=== Logiqx/caesar/dtd/caesar.dtd
<!--================ Character mnemonic entities =========================-->

<!ENTITY % HTMLlat1 PUBLIC
   "-//W3C//ENTITIES Latin 1 for XHTML//EN"
   "xhtml-lat1.ent">
%HTMLlat1;

<!ENTITY % HTMLsymbol PUBLIC
   "-//W3C//ENTITIES Symbols for XHTML//EN"
   "xhtml-symbol.ent">
%HTMLsymbol;

<!ENTITY % HTMLspecial PUBLIC
   "-//W3C//ENTITIES Special for XHTML//EN"
   "xhtml-special.ent">
%HTMLspecial;

<!--================ My structures =========================-->

<!ELEMENT emulator_link (name, version, date, homepage+, author_link+, emulates, comment, platform)>
<!ATTLIST emulator_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT old_name (name, emulator_link)>

<!ELEMENT author_link (name)>
<!ATTLIST author_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT library_link (name, version, date, homepage, author_link+, emulates, comment)>
<!ATTLIST library_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT tool_link (name, version, date, homepage, author_link+, comment)>
<!ATTLIST tool_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT name (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT emulates (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT crc (#PCDATA)>
<!ELEMENT mame (#PCDATA)>
<!ELEMENT rombuild (#PCDATA)>
<!ELEMENT homepage (#PCDATA)>
<!ATTLIST homepage status CDATA "">
<!ELEMENT comment (#PCDATA | a)*>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA "">
<!ELEMENT status (#PCDATA)>
<!ELEMENT platform (#PCDATA)>

<!ELEMENT author (name, email*, emulator_links?, contribution_links?, cpu_links?, graphics_links?, sound_links?, tool_links?)>
<!ELEMENT emulator_links (emulator_link*, old_name*)>
<!ELEMENT contribution_links (emulator_link+)>
<!ELEMENT cpu_links (library_link+)>
<!ELEMENT graphics_links (library_link+)>
<!ELEMENT sound_links (library_link+)>
<!ELEMENT library_links (library_link+)>
<!ELEMENT tool_links (tool_link+)>

<!ELEMENT emulator (name, version, date, homepage+, author_link+, contributors?,
	emulates, comment, status,
	cpu_links?, tool_links?, platform, controllers?, features, files?, relatives?, snaps?, game_links?)>
<!ATTLIST emulator dat CDATA "" dat_type CDATA "" id CDATA "" type CDATA "">
<!ELEMENT contributors (contributor+)>
<!ELEMENT contributor (author_link, comment?)>
<!ELEMENT controllers (controller+)>
<!ELEMENT controller (#PCDATA)>

<!ELEMENT features (sound?, source?, screendump?, hiscoresave?, savegame?,
	recordinput?, dips?, cheat?, autoframeskip?, throttle?, network?, recordsound?, rotate?)>
<!ELEMENT sound (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT screendump (#PCDATA)>
<!ELEMENT hiscoresave (#PCDATA)>
<!ELEMENT savegame (#PCDATA)>
<!ELEMENT recordinput (#PCDATA)>
<!ELEMENT dips (#PCDATA)>
<!ELEMENT cheat (#PCDATA)>
<!ELEMENT autoframeskip (#PCDATA)>
<!ELEMENT throttle (#PCDATA)>
<!ELEMENT network (#PCDATA)>
<!ELEMENT recordsound (#PCDATA)>
<!ELEMENT recordmovie (#PCDATA)>
<!ELEMENT rotate (#PCDATA)>

<!ELEMENT files (file+)>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file name CDATA "" size CDATA "">

<!ELEMENT relatives (predecessors?, derivative_of?, hybrid_of?, modification_of?, port_of?, alt_versions?, ports?, modified_versions?, derivatives?, successors?)>
<!ELEMENT predecessors (emulator_link+)>
<!ELEMENT derivative_of (emulator_link+)>
<!ELEMENT hybrid_of (emulator_link+)>
<!ELEMENT modification_of (emulator_link+)>
<!ELEMENT port_of (emulator_link+)>
<!ELEMENT alt_versions (emulator_link+)>
<!ELEMENT ports (emulator_link+)>
<!ELEMENT modified_versions (emulator_link+)>
<!ELEMENT derivatives (emulator_link+)>
<!ELEMENT successors (emulator_link+)>

<!ELEMENT game_groups (game_group+)>
<!ELEMENT game_group (name, manufacturer, year, non_mame, game_links)>
<!ATTLIST game_group id NMTOKEN "">
<!ELEMENT game_links (game_link+)>
<!ELEMENT game_link (name, manufacturer, year, size, non_mame?, emulator_link?)>
<!ELEMENT non_mame (#PCDATA)>
<!ATTLIST game_link emu_id NMTOKEN "" emu_type NMTOKEN "" game_id NMTOKEN "">

<!ELEMENT game (emulator_link, game_group_link, name, manufacturer, year, size, audio?, input?, video?, chips?, driver?, snaps?, roms?)>
<!ATTLIST game emu_id NMTOKEN "" emu_type NMTOKEN "" game_id NMTOKEN "">
<!ELEMENT game_contents (title, game_group_links)>
<!ELEMENT mame_games (title, game_links)>
<!ELEMENT game_group_links (game_group_link+)>
<!ELEMENT game_group_link (name, manufacturer, year, non_mame)>
<!ATTLIST game_group_link file_id NMTOKEN "" grp_id NMTOKEN "">
<!ELEMENT roms (rom+)>
<!ELEMENT rom (name, size, crc, mame, rombuild)>
<!ELEMENT snaps (snap+)>
<!ELEMENT snap (#PCDATA)>
<!ATTLIST snap width NMTOKEN "" height NMTOKEN "">
<!ELEMENT audio (channels?)>
<!ELEMENT channels (#PCDATA)>
<!ELEMENT input (players, control?, buttons?, coins?, service?, tilt?)>
<!ELEMENT players (#PCDATA)>
<!ELEMENT control (#PCDATA)>
<!ELEMENT buttons (#PCDATA)>
<!ELEMENT coins (#PCDATA)>
<!ELEMENT service (#PCDATA)>
<!ELEMENT tilt (#PCDATA)>
<!ELEMENT video (screen, orientation, x?, y?, colors?, freq)>
<!ELEMENT screen (#PCDATA)>
<!ELEMENT orientation (#PCDATA)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT colors (#PCDATA)>
<!ELEMENT freq (#PCDATA)>
<!ELEMENT chips (chip+)>
<!ELEMENT chip (type, name, clock?, flags?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT clock (#PCDATA)>
<!ELEMENT flags (#PCDATA)>
<!ELEMENT driver (status, color, sound)>
<!ELEMENT color (#PCDATA)>

<!ELEMENT library (name, version, date, homepage, author_link+, emulates, comment, emulator_links?, tool_links?, files?, library_relatives?)>
<!ATTLIST library id NMTOKEN "" type NMTOKEN "">

<!ELEMENT library_relatives (library_predecessors?, library_descendants?)>
<!ELEMENT library_predecessors (library_link+)>
<!ELEMENT library_descendants (library_link+)>

<!ELEMENT emulator_contents (title, comment, emulator_links?)>
<!ELEMENT library_contents (title, comment, library_links?)>
<!ELEMENT tool_contents (title, comment, tool_links?)>

<!ELEMENT tool (name, version, date, homepage, author_link+, comment, emulator_links?, library_links?, files?, tool_relatives?)>
<!ATTLIST tool id NMTOKEN "" type NMTOKEN "">

<!ELEMENT tool_relatives (tool_predecessors?, tool_descendants?)>
<!ELEMENT tool_predecessors (tool_link+)>
<!ELEMENT tool_descendants (tool_link+)>

=== Logiqx/caesar/data/emus/multi/rockulator_orig.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="rockulator_orig" type="multi" dat="Rock-ulator_v0.86">
	<name>Rockulator</name>
	<version>0.86</version>
	<date>29/04/1997</date>

	<homepage status="none"></homepage>
	<author_link id="brian_levine">&author_brian_levine;</author_link>

	<contributors>
		<contributor>
			<author_link id="ivan_mackintosh">&author_ivan_mackintosh;</author_link>
			<comment>Original Vanguard Emulator (v0.1)</comment>
		</contributor>
		<contributor>
			<author_link id="allard_van_der_bas">&author_allard_van_der_bas;</author_link>
			<comment>Ported the Vanguard Emulator to GCC (v0.2)</comment>
		</contributor>
		<contributor>
			<author_link id="martin_scragg">&author_martin_scragg;</author_link>
			<comment>Memory map, schematics and assorted help</comment>
		</contributor>
	</contributors>

	<emulates>Vanguard, Fantasy, Nibbler (all SNK)</emulates>
	<comment>Started life as the Vanguard Emulator by Ivan Mackintosh. Ported to GCC by Allard van der Bas then continued by Brian. Re-written in C++ to become Rockulator++.</comment>
	<status>Superceded</status>

	<cpu_links>
		<library_link id="multi6502" type="cpu">&library_multi6502;</library_link>
	</cpu_links>

	<tool_links>
		<tool_link id="djgpp" type="compilers">&tool_djgpp;</tool_link>
		<tool_link id="allegro" type="gfx_libs">&tool_allegro;</tool_link>
	</tool_links>

	<platform>DOS</platform>

	<controllers>
		<controller>Keyboard</controller>
		<controller>Joystick</controller>
	</controllers>

	<features>
		<sound>Partial</sound>
		<source>Yes</source>
		<screendump>Yes</screendump>
		<hiscoresave>Yes</hiscoresave>
		<savegame>Yes</savegame>
		<recordinput>No</recordinput>
		<dips>No</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
		<network>No</network>
		<recordsound>No</recordsound>
		<rotate>No</rotate>
	</features>

	<files>
		<file name="Rockulator V0.86 [Dos].zip">Emulator v0.086</file>
	</files>

	<relatives>
		<successors>
			<emulator_link id="rockulator" type="multi">&emulator_rockulator;</emulator_link>
		</successors>
	</relatives>
</emulator>

=== Logiqx/caesar/data/authors/hasbro_interactive.xml
<?xml version="1.0"?>
<!DOCTYPE author SYSTEM "../../dtd/caesar.dtd">
<author id="hasbro_interactive">
	<name>Hasbro Interactive</name>
	<email>customer_support@hasbro.com</email>
	<emulator_links>
		<emulator_link id="atari_arcade_hits_1" type="commercial">&emulator_atari_arcade_hits_1;</emulator_link>
		<emulator_link id="atari_arcade_hits_2" type="commercial">&emulator_atari_arcade_hits_2;</emulator_link>
		<emulator_link id="centipede_classic_mode" type="commercial">&emulator_centipede_classic_mode;</emulator_link>
		<emulator_link id="centipede_classic_mode_dc" type="dreamcast">&emulator_centipede_classic_mode_dc;</emulator_link>
		<emulator_link id="qbert_classic_mode" type="commercial">&emulator_qbert_classic_mode;</emulator_link>
		<emulator_link id="qbert_classic_mode_psx" type="psx">&emulator_qbert_classic_mode_psx;</emulator_link>
		<emulator_link id="qbert_classic_mode_dc" type="dreamcast">&emulator_qbert_classic_mode_dc;</emulator_link>
	</emulator_links>
</author>

=== Logiqx/caesar/data/libs/cpu/musashi.xml
<?xml version="1.0"?>
<!DOCTYPE library SYSTEM "../../../dtd/caesar.dtd">
<library id="musashi" type="cpu">
	<name>Musashi</name>
	<version>3.3.1</version>
	<date>03/02/2001</date>

	<homepage status="bad">http://members.nbci.com/kstenerud/musashi.html</homepage>
	<author_link id="karl_stenerud">&author_karl_stenerud;</author_link>

	<emulates>M68000 (Motorola)</emulates>
	<comment>Written to ANSI C specifications with the exception of inline function use. Portable and fast.</comment>

	<emulator_links>
		<emulator_link id="ace" type="multi">&emulator_ace;</emulator_link>
		<emulator_link id="dmame" type="multi2">&emulator_dmame;</emulator_link>
		<emulator_link id="mame" type="multi">&emulator_mame;</emulator_link>
		<emulator_link id="m1" type="sound">&emulator_m1;</emulator_link>
		<emulator_link id="rcps" type="arm">&emulator_rcps;</emulator_link>
		<emulator_link id="sega_system_24_emulator" type="multi">&emulator_sega_system_24_emulator;</emulator_link>
		<emulator_link id="viva_nonno" type="multi">&emulator_viva_nonno;</emulator_link>
	</emulator_links>

	<files>
		<file name="musashi331.zip">Emulator</file>
	</files>
</library>

=== Logiqx/caesar/data/emus/linux/sega_c2_linux.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="sega_c2_linux" type="linux" dat="dummy">
	<name>Sega System C2 Emulator (Linux)</name>
	<version>0.2b</version>
	<date>21/09/2000</date>

	<homepage status="bad">http://www.emulinks.de/</homepage>
	<author_link id="ulrich_hecht">&author_ulrich_hecht;</author_link>

	<emulates>Sega System C2 Games</emulates>
	<comment>Linux port of the Sega System C2 Emulator.</comment>
	<status>Dormant</status>

	<cpu_links>
		<library_link id="starscream" type="cpu">&library_starscream;</library_link>
	</cpu_links>

	<tool_links>
		<tool_link id="djgpp" type="compilers">&tool_djgpp;</tool_link>
		<tool_link id="allegro" type="gfx_libs">&tool_allegro;</tool_link>
		<tool_link id="seal" type="snd_libs">&tool_seal;</tool_link>
	</tool_links>

	<platform>Linux</platform>

	<controllers>
		<controller>Keyboard</controller>
		<controller>Joystick</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>Yes</source>
		<screendump>Yes</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>No</savegame>
		<recordinput>No</recordinput>
		<dips>No</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
	</features>

	<files>
		<file name="c2emu_bin.tar.gz">Emulator</file>
		<file name="c2emu_src.tar.gz">Source</file>
	</files>

	<relatives>
		<port_of>
			<emulator_link id="sega_system_c2" type="multi">&emulator_sega_system_c2;</emulator_link>
		</port_of>
	</relatives>
</emulator>

=== Logiqx/caesar/data/emus/multi/finalburn.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="finalburn" type="multi" dat="Final_Burn_v0.518">
	<name>Final Burn</name>
	<version>0.518</version>
	<date>14/10/2002</date>

	<homepage>http://www.finalburn.com/</homepage>
	<author_link id="dave_dtmnt">&author_dave_dtmnt;</author_link>

	<emulates>Sega and Capcom 68000 games</emulates>
	<comment>Originally called the 'After Burner Emulator', Final Burn soon added support for other Sega games on similar hardware. In addition to those it has also started supporting CPS-2 games and a few of the CPS-1 games.</comment>
	<status>Dormant</status>

	<cpu_links>
		<library_link id="doze" type="cpu">&library_doze;</library_link>
		<library_link id="a68k" type="cpu">&library_a68k;</library_link>
	</cpu_links>

	<tool_links>
		<tool_link id="msvc" type="compilers">&tool_msvc;</tool_link>
		<tool_link id="zlib" type="zip_libs">&tool_zlib;</tool_link>
	</tool_links>

	<platform>Windows</platform>

	<controllers>
		<controller>Keyboard</controller>
		<controller>Joystick</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>Yes</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>Yes</savegame>
		<recordinput>No</recordinput>
		<dips>Yes</dips>
		<cheat>No</cheat>
		<autoframeskip>Yes</autoframeskip>
		<throttle>Yes</throttle>
	</features>

	<files>
		<file name="fbn_0518.zip">Emulator</file>
		<file name="burn_0517.zip">Source v0.517 (Burn Library)</file>
		<file name="burner_0517.zip">Source v0.517 (GUI)</file>
	</files>

	<relatives>
		<ports>
			<emulator_link id="finalburn_linux" type="linux">&emulator_finalburn_linux;</emulator_link>
			<emulator_link id="finalburn_qnx" type="qnx">&emulator_finalburn_qnx;</emulator_link>
			<emulator_link id="finalburn_beos" type="beos">&emulator_finalburn_beos;</emulator_link>
		</ports>

		<successors>
			<emulator_link id="finalburnalpha" type="multi">&emulator_finalburnalpha;</emulator_link>
		</successors>
	</relatives>
</emulator>

=== Logiqx/caesar/data/emus/mac/centimupp.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="centimupp" type="mac" dat="CentiMu++_v1.0d9">
	<name>CentiMu++</name>
	<version>1.0d9</version>
	<date>13/01/2001</date>

	<homepage>http://www.squirrelsw.com/cats/emulation.html</homepage>
	<author_link id="nick_vellios">&author_nick_vellios;</author_link>

	<emulates>Centipede (Atari)</emulates>
	<comment>Written in C++</comment>
	<status>Dormant</status>

	<platform>Mac</platform>

	<controllers>
		<controller>Keyboard</controller>
	</controllers>

	<features>
		<sound>?</sound>
		<source>No</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>Yes</savegame>
		<recordinput>No</recordinput>
		<dips>No</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
		<network>No</network>
		<recordsound>No</recordsound>
		<rotate>No</rotate>
	</features>

	<files>
		<file name="CentiMu++_d9.sit">Emulator</file>
	</files>

	<relatives>
		<predecessors>
			<emulator_link id="centimu" type="mac">&emulator_centimu;</emulator_link>
		</predecessors>
	</relatives>
</emulator>

=== Logiqx/caesar/data/tools/zip_libs/zlib.xml
<?xml version="1.0"?>
<!DOCTYPE tool SYSTEM "../../../dtd/caesar.dtd">
<tool id="zlib" type="zip_libs">
	<name>zlib</name>
	<version>1.2.3</version>
	<date>18/07/2005</date>

	<homepage>http://www.gzip.org/zlib/</homepage>
	<author_link id="jean_loup_gailly">&author_jean_loup_gailly;</author_link>
	<author_link id="mark_adler">&author_mark_adler;</author_link>

	<comment>A general purpose data compression/decompression library</comment>

	<emulator_links>
		<emulator_link id="ace" type="multi">&emulator_ace;</emulator_link>
		<emulator_link id="cage" type="multi">&emulator_cage;</emulator_link>
		<emulator_link id="combatschool" type="single">&emulator_combatschool;</emulator_link>
		<emulator_link id="crystal_system_emulator" type="multi">&emulator_crystal_system_emulator;</emulator_link>
		<emulator_link id="dmame" type="multi2">&emulator_dmame;</emulator_link>
		<emulator_link id="emudx" type="multi">&emulator_emudx;</emulator_link>
		<emulator_link id="emudx32" type="multi2">&emulator_emudx32;</emulator_link>
		<emulator_link id="finalburn" type="multi">&emulator_finalburn;</emulator_link>
		<emulator_link id="finalburnalpha" type="multi">&emulator_finalburnalpha;</emulator_link>
		<emulator_link id="gngeo" type="linux">&emulator_gngeo;</emulator_link>
		<emulator_link id="hive" type="multi">&emulator_hive;</emulator_link>
		<emulator_link id="hornet" type="single">&emulator_hornet;</emulator_link>
		<emulator_link id="mame" type="multi">&emulator_mame;</emulator_link>
		<emulator_link id="mame32" type="multi2">&emulator_mame32;</emulator_link>
		<emulator_link id="modeler" type="multi">&emulator_modeler;</emulator_link>
		<emulator_link id="msega" type="fake">&emulator_msega;</emulator_link>
		<emulator_link id="nebula" type="multi">&emulator_nebula;</emulator_link>
		<emulator_link id="nebulam2" type="multi">&emulator_nebulam2;</emulator_link>
		<emulator_link id="nebula_jukebox" type="sound">&emulator_nebula_jukebox;</emulator_link>
		<emulator_link id="phmame" type="qnx">&emulator_phmame;</emulator_link>
		<emulator_link id="qplayer" type="sound">&emulator_qplayer;</emulator_link>
		<emulator_link id="radikal_bikers_emulator" type="single">&emulator_radikal_bikers_emulator;</emulator_link>
		<emulator_link id="raine" type="multi">&emulator_raine;</emulator_link>
		<emulator_link id="raine32" type="multi2">&emulator_raine32;</emulator_link>
		<emulator_link id="raine_beos" type="beos">&emulator_raine_beos;</emulator_link>
		<emulator_link id="raine_linux" type="linux">&emulator_raine_linux;</emulator_link>
		<emulator_link id="raine_linux_alt" type="linux2">&emulator_raine_linux_alt;</emulator_link>
		<emulator_link id="replay" type="multi">&emulator_replay;</emulator_link>
		<emulator_link id="retrocade" type="multi">&emulator_retrocade;</emulator_link>
		<emulator_link id="retrocade_os2" type="os2">&emulator_retrocade_os2;</emulator_link>
		<emulator_link id="s11emu" type="multi">&emulator_s11emu;</emulator_link>
		<emulator_link id="segamodel2emulator" type="multi">&emulator_segamodel2emulator;</emulator_link>
		<emulator_link id="sega_system_24_emulator" type="multi">&emulator_sega_system_24_emulator;</emulator_link>
		<emulator_link id="sega_system_c2" type="multi">&emulator_sega_system_c2;</emulator_link>
		<emulator_link id="sname" type="multi2">&emulator_sname;</emulator_link>
		<emulator_link id="snamew" type="multi">&emulator_snamew;</emulator_link>
		<emulator_link id="tickle" type="multi">&emulator_tickle;</emulator_link>
		<emulator_link id="vantage" type="multi">&emulator_vantage;</emulator_link>
		<emulator_link id="virtua" type="multi">&emulator_virtua;</emulator_link>
		<emulator_link id="kawaks" type="multi">&emulator_kawaks;</emulator_link>
		<emulator_link id="zinc" type="multi">&emulator_zinc;</emulator_link>
	</emulator_links>

	<files>
		<file name="zlib123.zip">zlib distribution</file>
	</files>
</tool>

=== Logiqx/caesar/data/emus/sound/cpse.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="cpse" type="sound" dat="CPSE_v0.02">
	<name>CPSE</name>
	<version>0.02</version>
	<date>19/11/2001</date>

	<homepage>http://cpse.emuunlim.com/</homepage>
	<author_link id="cesar_nicolas_gonzalez">&author_cesar_nicolas_gonzalez;</author_link>

	<emulates>QSound music of CPS-2 games</emulates>
	<comment>Plays the music and sound effects from arcade games based on Capcom's CPS-2 hardware. Also contains a sprite viewer and plans to become a full emulator eventually.</comment>
	<status>Dormant</status>

	<platform>DOS</platform>

	<controllers>
		<controller>Keyboard</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>No</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>No</savegame>
		<recordinput>No</recordinput>
		<dips>No</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>No</throttle>
		<network>No</network>
		<recordsound>No</recordsound>
		<rotate>No</rotate>
	</features>

	<files>
		<file name="cpse002.zip">Player for DOS</file>
	</files>
</emulator>
