=== Logiqx/caesar/dtd/caesar.dtd
<!--================ Character mnemonic entities =========================-->

<!ENTITY % HTMLlat1 PUBLIC
   "-//W3C//ENTITIES Latin 1 for XHTML//EN"
   "xhtml-lat1.ent">
%HTMLlat1;

<!ENTITY % HTMLsymbol PUBLIC
   "-//W3C//ENTITIES Symbols for XHTML//EN"
   "xhtml-symbol.ent">
%HTMLsymbol;

<!ENTITY % HTMLspecial PUBLIC
   "-//W3C//ENTITIES Special for XHTML//EN"
   "xhtml-special.ent">
%HTMLspecial;

<!--================ My structures =========================-->

<!ELEMENT emulator_link (name, version, date, homepage+, author_link+, emulates, comment, platform)>
<!ATTLIST emulator_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT old_name (name, emulator_link)>

<!ELEMENT author_link (name)>
<!ATTLIST author_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT library_link (name, version, date, homepage, author_link+, emulates, comment)>
<!ATTLIST library_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT tool_link (name, version, date, homepage, author_link+, comment)>
<!ATTLIST tool_link id NMTOKEN "" type NMTOKEN "">

<!ELEMENT name (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT emulates (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT crc (#PCDATA)>
<!ELEMENT mame (#PCDATA)>
<!ELEMENT rombuild (#PCDATA)>
<!ELEMENT homepage (#PCDATA)>
<!ATTLIST homepage status CDATA "">
<!ELEMENT comment (#PCDATA | a)*>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA "">
<!ELEMENT status (#PCDATA)>
<!ELEMENT platform (#PCDATA)>

<!ELEMENT author (name, email*, emulator_links?, contribution_links?, cpu_links?, graphics_links?, sound_links?, tool_links?)>
<!ELEMENT emulator_links (emulator_link*, old_name*)>
<!ELEMENT contribution_links (emulator_link+)>
<!ELEMENT cpu_links (library_link+)>
<!ELEMENT graphics_links (library_link+)>
<!ELEMENT sound_links (library_link+)>
<!ELEMENT library_links (library_link+)>
<!ELEMENT tool_links (tool_link+)>

<!ELEMENT emulator (name, version, date, homepage+, author_link+, contributors?,
	emulates, comment, status,
	cpu_links?, tool_links?, platform, controllers?, features, files?, relatives?, snaps?, game_links?)>
<!ATTLIST emulator dat CDATA "" dat_type CDATA "" id CDATA "" type CDATA "">
<!ELEMENT contributors (contributor+)>
<!ELEMENT contributor (author_link, comment?)>
<!ELEMENT controllers (controller+)>
<!ELEMENT controller (#PCDATA)>

<!ELEMENT features (sound?, source?, screendump?, hiscoresave?, savegame?,
	recordinput?, dips?, cheat?, autoframeskip?, throttle?, network?, recordsound?, rotate?)>
<!ELEMENT sound (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT screendump (#PCDATA)>
<!ELEMENT hiscoresave (#PCDATA)>
<!ELEMENT savegame (#PCDATA)>
<!ELEMENT recordinput (#PCDATA)>
<!ELEMENT dips (#PCDATA)>
<!ELEMENT cheat (#PCDATA)>
<!ELEMENT autoframeskip (#PCDATA)>
<!ELEMENT throttle (#PCDATA)>
<!ELEMENT network (#PCDATA)>
<!ELEMENT recordsound (#PCDATA)>
<!ELEMENT recordmovie (#PCDATA)>
<!ELEMENT rotate (#PCDATA)>

<!ELEMENT files (file+)>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file name CDATA "" size CDATA "">

<!ELEMENT relatives (predecessors?, derivative_of?, hybrid_of?, modification_of?, port_of?, alt_versions?, ports?, modified_versions?, derivatives?, successors?)>
<!ELEMENT predecessors (emulator_link+)>
<!ELEMENT derivative_of (emulator_link+)>
<!ELEMENT hybrid_of (emulator_link+)>
<!ELEMENT modification_of (emulator_link+)>
<!ELEMENT port_of (emulator_link+)>
<!ELEMENT alt_versions (emulator_link+)>
<!ELEMENT ports (emulator_link+)>
<!ELEMENT modified_versions (emulator_link+)>
<!ELEMENT derivatives (emulator_link+)>
<!ELEMENT successors (emulator_link+)>

<!ELEMENT game_groups (game_group+)>
<!ELEMENT game_group (name, manufacturer, year, non_mame, game_links)>
<!ATTLIST game_group id NMTOKEN "">
<!ELEMENT game_links (game_link+)>
<!ELEMENT game_link (name, manufacturer, year, size, non_mame?, emulator_link?)>
<!ELEMENT non_mame (#PCDATA)>
<!ATTLIST game_link emu_id NMTOKEN "" emu_type NMTOKEN "" game_id NMTOKEN "">

<!ELEMENT game (emulator_link, game_group_link, name, manufacturer, year, size, audio?, input?, video?, chips?, driver?, snaps?, roms?)>
<!ATTLIST game emu_id NMTOKEN "" emu_type NMTOKEN "" game_id NMTOKEN "">
<!ELEMENT game_contents (title, game_group_links)>
<!ELEMENT mame_games (title, game_links)>
<!ELEMENT game_group_links (game_group_link+)>
<!ELEMENT game_group_link (name, manufacturer, year, non_mame)>
<!ATTLIST game_group_link file_id NMTOKEN "" grp_id NMTOKEN "">
<!ELEMENT roms (rom+)>
<!ELEMENT rom (name, size, crc, mame, rombuild)>
<!ELEMENT snaps (snap+)>
<!ELEMENT snap (#PCDATA)>
<!ATTLIST snap width NMTOKEN "" height NMTOKEN "">
<!ELEMENT audio (channels?)>
<!ELEMENT channels (#PCDATA)>
<!ELEMENT input (players, control?, buttons?, coins?, service?, tilt?)>
<!ELEMENT players (#PCDATA)>
<!ELEMENT control (#PCDATA)>
<!ELEMENT buttons (#PCDATA)>
<!ELEMENT coins (#PCDATA)>
<!ELEMENT service (#PCDATA)>
<!ELEMENT tilt (#PCDATA)>
<!ELEMENT video (screen, orientation, x?, y?, colors?, freq)>
<!ELEMENT screen (#PCDATA)>
<!ELEMENT orientation (#PCDATA)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT colors (#PCDATA)>
<!ELEMENT freq (#PCDATA)>
<!ELEMENT chips (chip+)>
<!ELEMENT chip (type, name, clock?, flags?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT clock (#PCDATA)>
<!ELEMENT flags (#PCDATA)>
<!ELEMENT driver (status, color, sound)>
<!ELEMENT color (#PCDATA)>

<!ELEMENT library (name, version, date, homepage, author_link+, emulates, comment, emulator_links?, tool_links?, files?, library_relatives?)>
<!ATTLIST library id NMTOKEN "" type NMTOKEN "">

<!ELEMENT library_relatives (library_predecessors?, library_descendants?)>
<!ELEMENT library_predecessors (library_link+)>
<!ELEMENT library_descendants (library_link+)>

<!ELEMENT emulator_contents (title, comment, emulator_links?)>
<!ELEMENT library_contents (title, comment, library_links?)>
<!ELEMENT tool_contents (title, comment, tool_links?)>

<!ELEMENT tool (name, version, date, homepage, author_link+, comment, emulator_links?, library_links?, files?, tool_relatives?)>
<!ATTLIST tool id NMTOKEN "" type NMTOKEN "">

<!ELEMENT tool_relatives (tool_predecessors?, tool_descendants?)>
<!ELEMENT tool_predecessors (tool_link+)>
<!ELEMENT tool_descendants (tool_link+)>

=== Logiqx/caesar/data/emus/commercial/namco_history_vol_1.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="namco_history_vol_1" type="commercial" dat="Namco_History_Vol_1">
	<name>Namco History Vol 1</name>
	<version>-</version>
	<date>1997</date>

	<homepage>http://www.namco.co.jp/home/cs/pc/nh_vol1/</homepage>
	<author_link id="namco">&author_namco;</author_link>

	<emulates>Mappy, Xevious, Super Xevious, Toypop, Motos</emulates>
	<comment>Fully playable demos of Mappy and Xevious are available below. Very good emulation, includes ROMs and is freeware.</comment>
	<status>Released</status>

	<platform>Windows</platform>

	<controllers>
		<controller>Keyboard</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>No</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>No</savegame>
		<recordinput>No</recordinput>
		<dips>No</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
	</features>

	<files>
		<file name="mappy95.zip">Mappy Emulator (inbuilt ROMs)</file>
		<file name="xevious95.zip">Xevious Emulator (inbuilt ROMs)</file>
	</files>
</emulator>

=== Logiqx/caesar/data/emus/n64/namco_museum_64.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="namco_museum_64" type="n64" dat="Namco_Museum_64">
	<name>Namco Museum 64</name>
	<version>-</version>
	<date>1999</date>

	<homepage>http://www.namco.com/</homepage>
	<author_link id="namco">&author_namco;</author_link>

	<emulates>Galaga, Pac-Man, Pole Position, Galaxian, Dig Dug, Ms Pac-Man</emulates>
	<comment>A selection of classic games from Namco plus related information.</comment>
	<status>Released</status>

	<platform>N64</platform>

	<controllers>
		<controller>Joypad</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>No</source>
		<screendump>No</screendump>
		<hiscoresave>Yes</hiscoresave>
		<savegame>No</savegame>
		<recordinput>No</recordinput>
		<dips>Yes</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
		<rotate>Yes</rotate>
	</features>
</emulator>

=== Logiqx/caesar/data/tools/compilers/mingw.xml
<?xml version="1.0"?>
<!DOCTYPE tool SYSTEM "../../../dtd/caesar.dtd">
<tool id="mingw" type="compilers">
	<name>MinGW</name>
	<version>3.4.2</version>
	<date>13/01/2005</date>

	<homepage>http://sourceforge.net/projects/mingw/</homepage>
	<author_link id="mingw">&author_mingw;</author_link>

	<comment>Port of GNU C/C++ compiler for Windows</comment>

	<emulator_links>
		<emulator_link id="dice" type="multi">&emulator_dice;</emulator_link>
		<emulator_link id="finalburnalpha" type="multi">&emulator_finalburnalpha;</emulator_link>
		<emulator_link id="gxp" type="sound">&emulator_gxp;</emulator_link>
		<emulator_link id="mame" type="multi">&emulator_mame;</emulator_link>
		<emulator_link id="raine32" type="multi2">&emulator_raine32;</emulator_link>
		<emulator_link id="sega_system_24_emulator" type="multi">&emulator_sega_system_24_emulator;</emulator_link>
		<emulator_link id="snamew" type="multi">&emulator_snamew;</emulator_link>
		<emulator_link id="tickle" type="multi">&emulator_tickle;</emulator_link>
	</emulator_links>

	<files>
		<file name="gcc-core-3.4.2-20040916-1.tar.gz">GCC</file>
		<file name="binutils-2.15.91-20040904-1.tar.gz">binutils</file>
		<file name="mingw-runtime-3.9.tar.gz">MinGW Runtime</file>
		<file name="w32api-3.6.tar.gz">Windows API</file>
		<file name="gdb-5.2.1-1.exe">GDB (GNU Debugger)</file>
		<file name="MSYS-1.0.10.exe">MSYS 1.0.10</file>
		<file name="dx70_mgw.zip">DirectX 7.0 libraries and headers</file>
		<file name="upx125w.zip">UPX 1.25 for Windows (useful for compacting executables)</file>
	</files>
</tool>

=== Logiqx/caesar/data/emus/mac/yiear.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="yiear" type="mac" dat="Yie_Ar_Kung_Fu">
	<name>Yie Ar Kung Fu</name>
	<version>1.0</version>
	<date>09/11/1997</date>

	<homepage status="none"></homepage>
	<author_link id="phil_stroffolino">&author_phil_stroffolino;</author_link>

	<emulates>Yie Ar Kung Fu</emulates>
	<comment>This emulator perfectly plays the classic fighting arcade game, Yie Ar Kung-Fu. This emulator is fast even on slower machines. It perfectly renders the original graphics, except for a difference in a color here or there, and plays back all the sounds 100 percent true to the original.</comment>
	<status>Discontinued</status>

	<platform>Mac</platform>

	<controllers>
		<controller>Keyboard</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>No</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>No</savegame>
		<recordinput>No</recordinput>
		<dips>Yes</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
		<network>No</network>
		<recordsound>No</recordsound>
		<rotate>No</rotate>
	</features>

	<files>
		<file name="yakf.cpt.Hqx">Emulator (hqx)</file>
		<file name="YieAr.sit">Emulator (stuffit)</file>
	</files>
</emulator>

=== Logiqx/caesar/data/emus/psx.xml
<?xml version="1.0"?>
<!DOCTYPE emulator_contents SYSTEM "../../dtd/caesar.dtd">
<emulator_contents id="psx">
	<title>Emulators for the Playstation</title>
	<comment>These emulators are all for the Playstation</comment>
	<emulator_links>
		<emulator_link id="arcade_party_pak" type="psx">&emulator_arcade_party_pak;</emulator_link>
		<emulator_link id="atari_collection" type="psx">&emulator_atari_collection;</emulator_link>
		<emulator_link id="atari_collection_2" type="psx">&emulator_atari_collection_2;</emulator_link>
		<emulator_link id="midway_collection_2" type="psx">&emulator_midway_collection_2;</emulator_link>
		<emulator_link id="konami_arcade_classics" type="psx">&emulator_konami_arcade_classics;</emulator_link>
		<emulator_link id="namco_museum_encore" type="psx">&emulator_namco_museum_encore;</emulator_link>
		<emulator_link id="namco_museum_1" type="psx">&emulator_namco_museum_1;</emulator_link>
		<emulator_link id="namco_museum_2" type="psx">&emulator_namco_museum_2;</emulator_link>
		<emulator_link id="namco_museum_3" type="psx">&emulator_namco_museum_3;</emulator_link>
		<emulator_link id="namco_museum_4" type="psx">&emulator_namco_museum_4;</emulator_link>
		<emulator_link id="namco_museum_5" type="psx">&emulator_namco_museum_5;</emulator_link>
		<emulator_link id="qbert_classic_mode_psx" type="psx">&emulator_qbert_classic_mode_psx;</emulator_link>
		<emulator_link id="galaxian_project" type="psx">&emulator_galaxian_project;</emulator_link>
		<emulator_link id="phoenix_project" type="psx">&emulator_phoenix_project;</emulator_link>
		<emulator_link id="space_invaders_project" type="psx">&emulator_space_invaders_project;</emulator_link>
		<emulator_link id="williams_greatest_hits" type="psx">&emulator_williams_greatest_hits;</emulator_link>
	</emulator_links>
</emulator_contents>

=== Logiqx/caesar/data/emus/multi/laser.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="laser" type="multi" dat="Laser_v0.20a">
	<name>Laser (Lopantu's Arcade System Emulator)</name>
	<version>0.20</version>
	<date>30/07/2002</date>

	<homepage>http://laser.sourceforge.net/</homepage>
	<homepage>http://www.emucamp.com/laser/</homepage>
	<author_link id="lopantu">&author_lopantu;</author_link>

	<emulates>Midway 8080 based games like space invaders</emulates>
	<comment>Based on Sinvader by Mike Green</comment>
	<status>Dormant</status>

	<cpu_links>
		<library_link id="z80" type="cpu">&library_z80;</library_link>
		<library_link id="m6502" type="cpu">&library_m6502;</library_link>
	</cpu_links>

	<tool_links>
		<tool_link id="djgpp" type="compilers">&tool_djgpp;</tool_link>
		<tool_link id="allegro" type="gfx_libs">&tool_allegro;</tool_link>
	</tool_links>

	<platform>DOS</platform>

	<controllers>
		<controller>Keyboard</controller>
		<controller>Joystick</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>Yes</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>Yes</savegame>
		<recordinput>No</recordinput>
		<dips>No</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
		<rotate>No</rotate>
	</features>

	<files>
		<file name="laser020.zip">DOS Binary for Laser</file>
		<file name="laser020s.zip">DOS Source for Laser</file>
	</files>
	
	<relatives>
		<predecessors>
			<emulator_link id="sinvader" type="single">&emulator_sinvader;</emulator_link>
		</predecessors>

		<ports>
			<emulator_link id="laser32" type="multi2">&emulator_laser32;</emulator_link>
			<emulator_link id="belaser" type="beos">&emulator_belaser;</emulator_link>
			<emulator_link id="laser_ipaq" type="wince">&emulator_laser_ipaq;</emulator_link>
			<emulator_link id="laser_linux" type="linux">&emulator_laser_linux;</emulator_link>
			<emulator_link id="laserdc" type="dreamcast">&emulator_laserdc;</emulator_link>
			<emulator_link id="laser_sdl" type="multi2">&emulator_laser_sdl;</emulator_link>
		</ports>
	</relatives>
</emulator>

=== Logiqx/caesar/data/emus/os2/retrocade_os2.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="retrocade_os2" type="os2" dat="Retrocade_Alpha_5" dat_type="extra">
	<name>Retrocade (OS/2)</name>
	<version>Alpha 5</version>
	<date>20/08/2000</date>

	<homepage status="bad">http://emuos2.vintagegaming.com/</homepage>
	<author_link id="martin_amodeo">&author_martin_amodeo;</author_link>

	<emulates>Over 100 Classics (Late 70's to mid/late 80's)</emulates>
	<comment>Nice interface but everything is covered by MAME</comment>
	<status>Dormant</status>

	<cpu_links>
		<library_link id="mathbox" type="cpu">&library_mathbox;</library_link>
		<library_link id="multi6502" type="cpu">&library_multi6502;</library_link>
		<library_link id="multi6808" type="cpu">&library_multi6808;</library_link>
		<library_link id="multi6809" type="cpu">&library_multi6809;</library_link>
		<library_link id="multiz80" type="cpu">&library_multiz80;</library_link>
		<library_link id="starscream" type="cpu">&library_starscream;</library_link>
	</cpu_links>

	<tool_links>
		<tool_link id="zlib" type="zip_libs">&tool_zlib;</tool_link>
	</tool_links>

	<platform>OS/2</platform>

	<controllers>
		<controller>Keyboard</controller>
		<controller>Joystick</controller>
		<controller>Mouse</controller>
	</controllers>

	<features>
		<sound>Yes</sound>
		<source>No</source>
		<screendump>Yes</screendump>
		<hiscoresave>Yes</hiscoresave>
		<savegame>Yes</savegame>
		<recordinput>Yes</recordinput>
		<dips>Yes</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
		<network>No</network>
		<recordsound>No</recordsound>
		<rotate>No</rotate>
	</features>

	<files>
		<file name="retro_alpha5.zip">Emulator</file>
	</files>

	<relatives>
		<port_of>
			<emulator_link id="retrocade" type="multi">&emulator_retrocade;</emulator_link>
		</port_of>
	</relatives>
</emulator>

=== Logiqx/caesar/data/emus/linux/xcade_unix.xml
<?xml version="1.0"?>
<!DOCTYPE emulator SYSTEM "../../../dtd/caesar.dtd">
<emulator id="xcade_unix" type="linux" dat="Xcade_v0.85">
	<name>Xcade (Unix)</name>
	<version>0.85</version>
	<date>25/04/1997</date>

	<homepage status="none"></homepage>
	<author_link id="jeff_mitchell">&author_jeff_mitchell;</author_link>

	<contributors>
		<contributor>
			<author_link id="maximum_entropy">&author_maximum_entropy;</author_link>
			<comment>Patches for Space Invaders Deluxe and Lunar Rescue</comment>
		</contributor>
	</contributors>

	<emulates>Classics like Phoenix, Donkey Kong, Pac-Man and Space Invaders</emulates>
	<comment></comment>
	<status>Dormant</status>

	<platform>Linux</platform>

	<controllers>
		<controller>Keyboard</controller>
	</controllers>

	<features>
		<sound>No</sound>
		<source>No</source>
		<screendump>No</screendump>
		<hiscoresave>No</hiscoresave>
		<savegame>No</savegame>
		<recordinput>No</recordinput>
		<dips>No</dips>
		<cheat>No</cheat>
		<autoframeskip>No</autoframeskip>
		<throttle>Yes</throttle>
		<network>No</network>
	</features>

	<files>
		<file name="xcade085_fixed.tgz">Emulator (fixed archive, many on the web are corrupt)</file>
	</files>

	<relatives>
		<ports>
			<emulator_link id="xcade" type="multi">&emulator_xcade;</emulator_link>
			<emulator_link id="xcade_palmos" type="palmos">&emulator_xcade_palmos;</emulator_link>
		</ports>
	</relatives>
</emulator>
